name: next-starter

services:
  next-starter:
    image: next-starter:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - minio

  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-26T20-48-21Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data:/data
  

