name: next-starter-develop

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-26T20-48-21Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data:/data

